#doctrine:
#    orm:
#        entity_managers:
#            default:
#                mappings:
#                    AlsarXyzApplicationDomainBundle:
#                        type:                 yml
#                        prefix:               Alsar\Xyz\Domain\Model